name: build,tag,and push to ecr

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4  # Use the version of Terraform you want use
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Adjust the region as needed

    - name: Initialize Terraform
      run: terraform init

    # - name: Plan Terraform changes
    #   run: terraform plan 

    # - name: Apply Terraform changes
    #   run: terraform apply -auto-approve