name: Push to ECR

on:
  workflow_dispatch:

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: demo-app-repo
        IMAGE_TAG: sample_image
      run: |
        cat Dockerfile | docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG